### ISSUE TITLE
Container support

### ISSUE THREAD

**Issue by fredericlepied** [depends-on/depends-on-action#17]
- from stage 1, pass the `container` input and export the data from the PR to be reused by stage2.
- Add a boolean input `container` that can be let unset and on this case it is auto-detecting if there is a `Dockerfile` in the directory of the main change.
- when `container` is `true`, do not use the change from the local directories but point to the changes on github to allow the build of containers to work. For example, in python, instead of using `-e ../<dir>` use `pkg @ git+https://github.com/<org>/<repo>@<branch>` in the `requirements.txt` substitution. Same thing for the other languages.

**Comment by leseb** [comment]
Is it already present?

**Comment by fredericlepied** [comment]
yes it is. Closing the issue.
