### ISSUE TITLE
Why pyyaml?

### ISSUE THREAD

**Issue by leseb** [depends-on/depends-on-action#53]
Where and why is pyyaml needed? It's not used anywhere in the project as far as I can tell...

**Comment by leseb** [comment]
https://github.com/depends-on/depends-on-action/blob/ce4047f663174688ea42a21fac1b1007d97b79bb/depends_on_stage2#L161-L162

**Comment by fredericlepied** [comment]
It is needed for Ansible: https://github.com/depends-on/depends-on-action/blob/main/depends_on/ansible.py#L5

**Comment by leseb** [comment]
Ok thanks, https://github.com/depends-on/depends-on-action/pull/52/commits/88ff3f46db82479d5ec81c09968024d09290972a adds the dep to the project.
